# Generated by Django 5.1.6 on 2026-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('admin_registration', 'Admin Registration'), ('password_reset', 'Password Reset'), ('company_password_change', 'Company Password Change'), ('company_email_change', 'Company Email Change'), ('company_mobile_change', 'Company Mobile Change'), ('company_delete_account', 'Company Delete Account')], max_length=32),
        ),
    ]
