# Generated by Django 6.0.5 on 2026-06-30 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_community_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitymessage',
            new_name='chat_commun_topic_i_70397f_idx',
            old_name='chat_commun_topic_i_7ae5c1_idx',
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communitytopic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
