from django.urls import path

from apps.accounts.views import (
    AccountSettingsAPIView,
    AdminRegisterAPIView,
    AdminRegisterVerifyAPIView,
    ChangeEmailAPIView,
    ChangeMobileNumberAPIView,
    ChangePasswordAPIView,
    CompanySettingsOTPConfirmAPIView,
    CompanySettingsOTPRequestAPIView,
    CompanyRegistrationLookupAPIView,
    CorpersTokenObtainPairView,
    CorpersTokenRefreshView,
    DeleteAccountAPIView,
    ForgotPasswordAPIView,
    LogoutAPIView,
    MeAPIView,
    ProfileVisibilityAPIView,
    ReactivationResolveAPIView,
    RegisterAPIView,
    ResendOTPAPIView,
    ResetPasswordAPIView,
    VerifyPasswordResetCodeAPIView,
    VerifyEmailAPIView,
)

urlpatterns = [
    path(
        "company-registration-lookup/",
        CompanyRegistrationLookupAPIView.as_view(),
        name="company-registration-lookup",
    ),
    path("register/", RegisterAPIView.as_view(), name="register"),
    path("admin/register/", AdminRegisterAPIView.as_view(), name="admin-register"),
    path("admin/register/verify/", AdminRegisterVerifyAPIView.as_view(), name="admin-register-verify"),
    path("verify-email/", VerifyEmailAPIView.as_view(), name="verify-email"),
    path("resend-otp/", ResendOTPAPIView.as_view(), name="resend-otp"),
    path("login/", CorpersTokenObtainPairView.as_view(), name="login"),
    path("logout/", LogoutAPIView.as_view(), name="logout"),
    path("token/refresh/", CorpersTokenRefreshView.as_view(), name="token-refresh"),
    path("forgot-password/", ForgotPasswordAPIView.as_view(), name="forgot-password"),
    path("reset-password/verify-code/", VerifyPasswordResetCodeAPIView.as_view(), name="reset-password-verify-code"),
    path("reset-password/", ResetPasswordAPIView.as_view(), name="reset-password"),
    path("reactivation/resolve/", ReactivationResolveAPIView.as_view(), name="reactivation-resolve"),
    path("me/", MeAPIView.as_view(), name="me"),
    path("settings/", AccountSettingsAPIView.as_view(), name="settings"),
    path("settings/profile-visibility/", ProfileVisibilityAPIView.as_view(), name="profile-visibility"),
    path("settings/change-password/", ChangePasswordAPIView.as_view(), name="change-password"),
    path("settings/change-email/", ChangeEmailAPIView.as_view(), name="change-email"),
    path(
        "settings/company-otp/request/",
        CompanySettingsOTPRequestAPIView.as_view(),
        name="company-settings-otp-request",
    ),
    path(
        "settings/company-otp/confirm/",
        CompanySettingsOTPConfirmAPIView.as_view(),
        name="company-settings-otp-confirm",
    ),
    path(
        "settings/change-mobile-number/",
        ChangeMobileNumberAPIView.as_view(),
        name="change-mobile-number",
    ),
    path("settings/delete-account/", DeleteAccountAPIView.as_view(), name="delete-account"),
]
