# Generated by Django 5.0.2 on 2026-03-09 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sector', 'Sector'), ('university', 'University'), ('degree', 'Degree'), ('posting_location', 'Posting Location')], max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='platformoption',
            constraint=models.UniqueConstraint(fields=('category', 'value'), name='unique_platform_option'),
        ),
    ]
