# Generated by Django 5.1.6 on 2026-06-08 09:39

from django.db import migrations, models


def backfill_company_approval_status(apps, schema_editor):
    CompanyProfile = apps.get_model('companies', 'CompanyProfile')
    for company in CompanyProfile.objects.all().iterator():
        if (
            company.verification_status == 'verified'
            and company.terms_of_agreement_accepted_at
            and company.terms_of_use_accepted_at
        ):
            next_status = 'approved'
        elif (
            company.verification_status == 'pending'
            and company.terms_of_agreement_accepted_at
            and company.terms_of_use_accepted_at
        ):
            next_status = 'pending'
        elif company.verification_status == 'rejected':
            next_status = 'rejected'
        else:
            next_status = 'unsubmitted'

        CompanyProfile.objects.filter(pk=company.pk).update(approval_status=next_status)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_company_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='approval_status',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unsubmitted', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_company_approval_status, migrations.RunPython.noop),
    ]
