# Generated by Django 5.1.6 on 2026-06-08 09:39

from django.db import migrations, models


def backfill_corper_approval_status(apps, schema_editor):
    CorperProfile = apps.get_model('corpers', 'CorperProfile')
    for corper in CorperProfile.objects.all().iterator():
        if (
            corper.verification_status == 'verified'
            and corper.terms_of_agreement_accepted_at
            and corper.terms_of_use_accepted_at
        ):
            next_status = 'approved'
        elif (
            corper.verification_status in {'pending', 'under_review'}
            and corper.terms_of_agreement_accepted_at
            and corper.terms_of_use_accepted_at
        ):
            next_status = 'pending'
        elif corper.verification_status == 'rejected':
            next_status = 'rejected'
        else:
            next_status = 'unsubmitted'

        CorperProfile.objects.filter(pk=corper.pk).update(approval_status=next_status)


class Migration(migrations.Migration):

    dependencies = [
        ('corpers', '0002_corperprofile_identity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='corperprofile',
            name='approval_status',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unsubmitted', max_length=20),
        ),
        migrations.AddField(
            model_name='corperprofile',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_corper_approval_status, migrations.RunPython.noop),
    ]
